import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
const kMainColor = Color(0xfff2c131);
const kWhiteColor = Colors.white;
const kLogo = 'assets/images/logo.png';
const kUnActiveColor=Colors.lightBlueAccent;//Color(0xdff4dc8c);
const kfontfamily='Pacifico';
const kfontfamily2='Cairo';
const kfontfamily3='Amiri';
const url='https://aya.epaysadaka.com/api/';
const kKeepMeLoggedIn="loginstate";
const Ktoast=Color(0xfff2c131);